### ISSUE TITLE
Make the lib scraper callable without going through HTTP

### ISSUE THREAD

**Issue by anacrolix** [jpillora/scraper#1]
It might be useful to be able to directly call an Endpoint, per the behaviour currently in Handler.execute. The output of the call can be the interface{} that Handler.ServeHTTP is marshalling.

**Comment by jpillora** [comment]
So you mean expose: `Endpoint.Execute(html) (interface{}, error)`?

**Comment by anacrolix** [comment]
Precisely

**Comment by anacrolix** [comment]
Wait, I think possibly let it do the fetch for you still by default, maybe another function that takes the HTML you give.

**Comment by anacrolix** [comment]
Endpoint.Execute() (interface{}, error)
Endpoint.ExecuteHTML(html) (interface{}, error)

**Comment by jpillora** [comment]
I think it'd be:

```
s := &scraper.Handler{}
...
s.Execute(endpoint string)
s.ExecuteHTML(endpoint, html string)
```

So what's the usecase? How will you make use of `interface{}`? might sense to instead return `[]result`

**Comment by anacrolix** [comment]
My justification there was that if there is no List set in Endpoint, the result isn't also a list. Per the current behaviour.

**Comment by jpillora** [comment]
I can expose type result aswell. The result can be a slice or a single
item, so if i make it the underlying method always return a slice, then in
HTTP handler, i can do:

var slice = s.Endpoint(id)
var out interface
if len(slice) == 1 {
   out = slice[0]
} else {
   out = slice
}

**Comment by anacrolix** [comment]
If you mean the Endpoint methods will return []Result (or whatever you export the type as), sounds great.

**Comment by jpillora** [comment]
Yep :+1: will do when I get a chance

**Comment by PouuleT** [comment]
Hello!
Did you have a chance  to introduce this change?
Is it still planned ? =)
Do you need a hand?

**Comment by jpillora** [comment]
Owow, totally forgot about this! Sure, I'd be happy to accept a PR. Looks the API required would be something like:

```
Execute(path string, params map[string]string) ([]Result, error)
```

Where `Result` is also `map[string]string`. I might have missed something though how's that sound?

**Comment by PouuleT** [comment]
Yep!
Is it better to take a 'path' as string as you proposed or directly a *Endpoint just like the current execute function and let the user of the lib take care of managing its Endpoints ?

Any preferences?

**Comment by jpillora** [comment]
Ah yes we can drop `path` from `Execute` and it can be an `Endpoint` method instead. Then:

```
e := s.Endpoint("/search")
e.Execute(params)
```

To maintain the existing API, we should leave`Endpoints` within `Config` and a helper `scraper.Endpoint` which returns `*Endpoint`, `nil` if missing.

**Comment by PouuleT** [comment]
Ok!
Only problems left are Log / Debug and Headers attributes of the Handler that, if executed from the Endpoint, are now unreachable
Shall I port them into the Enpoint as well ? Debug attribute is already there, Headers also, I'm not sure about the difference between Log and Debug though =)

**Comment by jpillora** [comment]
Hmm I think we should just publicise `Endpoint.debug` -> `Debug`. I think `Log bool` means verbose, and `Debug bool` means very verbose.

**Comment by jpillora** [comment]
Closed by https://github.com/jpillora/scraper/pull/3
